# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Connection do
  @moduledoc """
  Handle Tesla connections for DockerEngineAPI.
  """

  use Tesla

  # Add any middleware here (authentication)
  # plug(Tesla.Middleware.BaseUrl, "http://localhost:2356")
  # plug(Tesla.Middleware.Headers, %{"User-Agent" => "Elixir"})
  # plug(Tesla.Middleware.EncodeJson)

  @doc """
  Configure an authless client connection

  # Returns

  Tesla.Env.client
  """
  def new do
    middleware = [
      {Tesla.Middleware.BaseUrl, "http://localhost:2356"},
      {Tesla.Middleware.Headers, [{"User-Agent", "Elixir"}]},
      Tesla.Middleware.JSON
    ]

    Tesla.client(middleware)
  end
end
