# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Api.Distribution do
  @moduledoc """
  API calls for all endpoints tagged `Distribution`.
  """

  alias DockerEngineAPI.Connection
  import DockerEngineAPI.RequestBuilder


  @doc """
  Get image information from the registry
  Return image digest and platform information by contacting the registry. 

  ## Parameters

  - connection (DockerEngineAPI.Connection): Connection to server
  - name (String.t): Image name or id
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %DockerEngineAPI.Model.DistributionInspect{}} on success
  {:error, info} on failure
  """
  @spec distribution_inspect(Tesla.Env.client, String.t, keyword()) :: {:ok, DockerEngineAPI.Model.DistributionInspect.t} | {:error, Tesla.Env.t}
  def distribution_inspect(connection, name, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/distribution/#{name}/json")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%DockerEngineAPI.Model.DistributionInspect{})
  end
end
