# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Api.Secret do
  @moduledoc """
  API calls for all endpoints tagged `Secret`.
  """

  alias DockerEngineAPI.Connection
  import DockerEngineAPI.RequestBuilder

  @doc """
  Create a secret

  ## Parameters

  - connection (DockerEngineAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
    - :body (object): 

  ## Returns

  {:ok, %DockerEngineAPI.Model.IdResponse{}} on success
  {:error, info} on failure
  """
  def secret_create(connection, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    %{}
    |> method(:post)
    |> url("/secrets/create")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%DockerEngineAPI.Model.IdResponse{})
  end

  @doc """
  Delete a secret

  ## Parameters

  - connection (DockerEngineAPI.Connection): Connection to server
  - id (String.t): ID of the secret
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %{}} on success
  {:error, info} on failure
  """
  def secret_delete(connection, id, _opts \\ []) do
    %{}
    |> method(:delete)
    |> url("/secrets/#{id}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(false)
  end

  @doc """
  Inspect a secret

  ## Parameters

  - connection (DockerEngineAPI.Connection): Connection to server
  - id (String.t): ID of the secret
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %DockerEngineAPI.Model.Secret{}} on success
  {:error, info} on failure
  """
  def secret_inspect(connection, id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/secrets/#{id}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%DockerEngineAPI.Model.Secret{})
  end

  @doc """
  List secrets

  ## Parameters

  - connection (DockerEngineAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
    - :filters (String.t): A JSON encoded value of the filters (a &#x60;map[string][]string&#x60;) to process on the secrets list.  Available filters:  - &#x60;id&#x3D;&lt;secret id&gt;&#x60; - &#x60;label&#x3D;&lt;key&gt; or label&#x3D;&lt;key&gt;&#x3D;value&#x60; - &#x60;name&#x3D;&lt;secret name&gt;&#x60; - &#x60;names&#x3D;&lt;secret name&gt;&#x60; 

  ## Returns

  {:ok, [%Secret{}, ...]} on success
  {:error, info} on failure
  """
  def secret_list(connection, opts \\ []) do
    optional_params = %{
      :filters => :query
    }

    %{}
    |> method(:get)
    |> url("/secrets")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode([%DockerEngineAPI.Model.Secret{}])
  end

  @doc """
  Update a Secret

  ## Parameters

  - connection (DockerEngineAPI.Connection): Connection to server
  - id (String.t): The ID or name of the secret
  - version (integer()): The version number of the secret object being updated. This is required to avoid conflicting writes. 
  - opts (KeywordList): [optional] Optional parameters
    - :body (SecretSpec): The spec of the secret to update. Currently, only the Labels field can be updated. All other fields must remain unchanged from the [SecretInspect endpoint](#operation/SecretInspect) response values. 

  ## Returns

  {:ok, %{}} on success
  {:error, info} on failure
  """
  def secret_update(connection, id, version, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    %{}
    |> method(:post)
    |> url("/secrets/#{id}/update")
    |> add_param(:query, :version, version)
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(false)
  end
end
