# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.BuildCache do
  @moduledoc """
  BuildCache contains information about a build cache record. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ID",
    :"Parent",
    :"Parents",
    :"Type",
    :"Description",
    :"InUse",
    :"Shared",
    :"Size",
    :"CreatedAt",
    :"LastUsedAt",
    :"UsageCount"
  ]

  @type t :: %__MODULE__{
    :"ID" => String.t,
    :"Parent" => String.t,
    :"Parents" => [String.t],
    :"Type" => String.t,
    :"Description" => String.t,
    :"InUse" => boolean(),
    :"Shared" => boolean(),
    :"Size" => integer(),
    :"CreatedAt" => String.t,
    :"LastUsedAt" => String.t,
    :"UsageCount" => integer()
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.BuildCache do
  def decode(value, _options) do
    value
  end
end

