# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ChangeType do
  @moduledoc """
  Kind of change  Can be one of:  - &#x60;0&#x60;: Modified (\&quot;C\&quot;) - &#x60;1&#x60;: Added (\&quot;A\&quot;) - &#x60;2&#x60;: Deleted (\&quot;D\&quot;) 
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ChangeType do
  def decode(value, _options) do
    value
  end
end

