# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ClusterVolumePublishStatus do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"NodeID",
    :"State",
    :"PublishContext"
  ]

  @type t :: %__MODULE__{
    :"NodeID" => String.t,
    :"State" => String.t,
    :"PublishContext" => %{optional(String.t) => String.t}
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ClusterVolumePublishStatus do
  def decode(value, _options) do
    value
  end
end

