# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ClusterVolumeSpecAccessMode do
  @moduledoc """
  Defines how the volume is used by tasks. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Scope",
    :"Sharing",
    :"MountVolume",
    :"Secrets",
    :"AccessibilityRequirements",
    :"CapacityRange",
    :"Availability"
  ]

  @type t :: %__MODULE__{
    :"Scope" => String.t,
    :"Sharing" => String.t,
    :"MountVolume" => Object,
    :"Secrets" => [ClusterVolumeSpecAccessModeSecrets],
    :"AccessibilityRequirements" => ClusterVolumeSpecAccessModeAccessibilityRequirements,
    :"CapacityRange" => ClusterVolumeSpecAccessModeCapacityRange,
    :"Availability" => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ClusterVolumeSpecAccessMode do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"MountVolume", :struct, DockerEngineAPI.Model.Object, options)
    |> deserialize(:"Secrets", :list, DockerEngineAPI.Model.ClusterVolumeSpecAccessModeSecrets, options)
    |> deserialize(:"AccessibilityRequirements", :struct, DockerEngineAPI.Model.ClusterVolumeSpecAccessModeAccessibilityRequirements, options)
    |> deserialize(:"CapacityRange", :struct, DockerEngineAPI.Model.ClusterVolumeSpecAccessModeCapacityRange, options)
  end
end

