# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ClusterVolume do
  @moduledoc """
  Options and information specific to, and only present on, Swarm CSI cluster volumes. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ID",
    :"Version",
    :"CreatedAt",
    :"UpdatedAt",
    :"Spec",
    :"Info",
    :"PublishStatus"
  ]

  @type t :: %__MODULE__{
    :"ID" => String.t,
    :"Version" => ObjectVersion,
    :"CreatedAt" => String.t,
    :"UpdatedAt" => String.t,
    :"Spec" => ClusterVolumeSpec,
    :"Info" => ClusterVolumeInfo,
    :"PublishStatus" => [ClusterVolumePublishStatus]
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ClusterVolume do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Version", :struct, DockerEngineAPI.Model.ObjectVersion, options)
    |> deserialize(:"Spec", :struct, DockerEngineAPI.Model.ClusterVolumeSpec, options)
    |> deserialize(:"Info", :struct, DockerEngineAPI.Model.ClusterVolumeInfo, options)
    |> deserialize(:"PublishStatus", :list, DockerEngineAPI.Model.ClusterVolumePublishStatus, options)
  end
end

