# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ClusterVolumeSpecAccessModeCapacityRange do
  @moduledoc """
  The desired capacity that the volume should be created with. If empty, the plugin will decide the capacity. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :RequiredBytes,
    :LimitBytes
  ]

  @type t :: %__MODULE__{
          :RequiredBytes => integer(),
          :LimitBytes => integer()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ClusterVolumeSpecAccessModeCapacityRange do
  def decode(value, _options) do
    value
  end
end
