# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ClusterVolumeInfo do
  @moduledoc """
  Information about the global status of the volume. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :CapacityBytes,
    :VolumeContext,
    :VolumeID,
    :AccessibleTopology
  ]

  @type t :: %__MODULE__{
          :CapacityBytes => integer(),
          :VolumeContext => %{optional(String.t()) => String.t()},
          :VolumeID => String.t(),
          :AccessibleTopology => [Topology]
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ClusterVolumeInfo do
  import DockerEngineAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:AccessibleTopology, :list, DockerEngineAPI.Model.Topology, options)
  end
end
