# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ContainerState do
  @moduledoc """
  ContainerState stores container&#39;s running state. It&#39;s part of ContainerJSONBase and will be returned by the \&quot;inspect\&quot; command. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :Status,
    :Running,
    :Paused,
    :Restarting,
    :OOMKilled,
    :Dead,
    :Pid,
    :ExitCode,
    :Error,
    :StartedAt,
    :FinishedAt,
    :Health
  ]

  @type t :: %__MODULE__{
          :Status => String.t(),
          :Running => boolean(),
          :Paused => boolean(),
          :Restarting => boolean(),
          :OOMKilled => boolean(),
          :Dead => boolean(),
          :Pid => integer(),
          :ExitCode => integer(),
          :Error => String.t(),
          :StartedAt => String.t(),
          :FinishedAt => String.t(),
          :Health => Health
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ContainerState do
  import DockerEngineAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Health, :struct, DockerEngineAPI.Model.Health, options)
  end
end
