# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ContainerWaitExitError do
  @moduledoc """
  container waiting error, if any
  """

  @derive [Poison.Encoder]
  defstruct [
    :Message
  ]

  @type t :: %__MODULE__{
          :Message => String.t()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ContainerWaitExitError do
  def decode(value, _options) do
    value
  end
end
