# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ContainerSummaryNetworkSettings do
  @moduledoc """
  A summary of the container&#39;s network settings
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Networks"
  ]

  @type t :: %__MODULE__{
    :"Networks" => %{optional(String.t) => EndpointSettings}
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ContainerSummaryNetworkSettings do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Networks", :map, DockerEngineAPI.Model.EndpointSettings, options)
  end
end

