# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.DeviceMapping do
  @moduledoc """
  A device mapping between the host and container
  """

  @derive [Poison.Encoder]
  defstruct [
    :"PathOnHost",
    :"PathInContainer",
    :"CgroupPermissions"
  ]

  @type t :: %__MODULE__{
    :"PathOnHost" => String.t,
    :"PathInContainer" => String.t,
    :"CgroupPermissions" => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.DeviceMapping do
  def decode(value, _options) do
    value
  end
end

