# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.DeviceRequest do
  @moduledoc """
  A request for devices to be sent to device drivers
  """

  @derive [Poison.Encoder]
  defstruct [
    :Driver,
    :Count,
    :DeviceIDs,
    :Capabilities,
    :Options
  ]

  @type t :: %__MODULE__{
          :Driver => String.t(),
          :Count => integer(),
          :DeviceIDs => [String.t()],
          :Capabilities => [[String.t()]],
          :Options => %{optional(String.t()) => String.t()}
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.DeviceRequest do
  def decode(value, _options) do
    value
  end
end
