# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.DistributionInspect do
  @moduledoc """
  Describes the result obtained from contacting the registry to retrieve image metadata. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Descriptor",
    :"Platforms"
  ]

  @type t :: %__MODULE__{
    :"Descriptor" => OciDescriptor,
    :"Platforms" => [OciPlatform]
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.DistributionInspect do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Descriptor", :struct, DockerEngineAPI.Model.OciDescriptor, options)
    |> deserialize(:"Platforms", :list, DockerEngineAPI.Model.OciPlatform, options)
  end
end

