# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.EndpointPortConfig do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :Protocol,
    :TargetPort,
    :PublishedPort,
    :PublishMode
  ]

  @type t :: %__MODULE__{
          :Name => String.t(),
          :Protocol => String.t(),
          :TargetPort => integer(),
          :PublishedPort => integer(),
          :PublishMode => String.t()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.EndpointPortConfig do
  def decode(value, _options) do
    value
  end
end
