# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.EndpointIpamConfig do
  @moduledoc """
  EndpointIPAMConfig represents an endpoint&#39;s IPAM configuration. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :IPv4Address,
    :IPv6Address,
    :LinkLocalIPs
  ]

  @type t :: %__MODULE__{
          :IPv4Address => String.t(),
          :IPv6Address => String.t(),
          :LinkLocalIPs => [String.t()]
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.EndpointIpamConfig do
  def decode(value, _options) do
    value
  end
end
