# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.EndpointSpec do
  @moduledoc """
  Properties that can be configured to access and load balance a service.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Mode",
    :"Ports"
  ]

  @type t :: %__MODULE__{
    :"Mode" => String.t,
    :"Ports" => [EndpointPortConfig]
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.EndpointSpec do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Ports", :list, DockerEngineAPI.Model.EndpointPortConfig, options)
  end
end

