# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.EngineDescription do
  @moduledoc """
  EngineDescription provides information about an engine.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"EngineVersion",
    :"Labels",
    :"Plugins"
  ]

  @type t :: %__MODULE__{
    :"EngineVersion" => String.t,
    :"Labels" => %{optional(String.t) => String.t},
    :"Plugins" => [EngineDescriptionPlugins]
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.EngineDescription do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Plugins", :list, DockerEngineAPI.Model.EngineDescriptionPlugins, options)
  end
end

