# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ErrorResponse do
  @moduledoc """
  Represents an error.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"message"
  ]

  @type t :: %__MODULE__{
    :"message" => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ErrorResponse do
  def decode(value, _options) do
    value
  end
end

