# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ErrorDetail do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :code,
    :message
  ]

  @type t :: %__MODULE__{
          :code => integer(),
          :message => String.t()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ErrorDetail do
  def decode(value, _options) do
    value
  end
end
