# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.EventMessage do
  @moduledoc """
  EventMessage represents the information an event contains. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :Type,
    :Action,
    :Actor,
    :scope,
    :time,
    :timeNano
  ]

  @type t :: %__MODULE__{
          :Type => String.t(),
          :Action => String.t(),
          :Actor => EventActor,
          :scope => String.t(),
          :time => integer(),
          :timeNano => integer()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.EventMessage do
  import DockerEngineAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Actor, :struct, DockerEngineAPI.Model.EventActor, options)
  end
end
