# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ExecConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"AttachStdin",
    :"AttachStdout",
    :"AttachStderr",
    :"ConsoleSize",
    :"DetachKeys",
    :"Tty",
    :"Env",
    :"Cmd",
    :"Privileged",
    :"User",
    :"WorkingDir"
  ]

  @type t :: %__MODULE__{
    :"AttachStdin" => boolean(),
    :"AttachStdout" => boolean(),
    :"AttachStderr" => boolean(),
    :"ConsoleSize" => [integer()],
    :"DetachKeys" => String.t,
    :"Tty" => boolean(),
    :"Env" => [String.t],
    :"Cmd" => [String.t],
    :"Privileged" => boolean(),
    :"User" => String.t,
    :"WorkingDir" => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ExecConfig do
  def decode(value, _options) do
    value
  end
end

