# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.GraphDriverData do
  @moduledoc """
  Information about the storage driver used to store the container&#39;s and image&#39;s filesystem. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Name",
    :"Data"
  ]

  @type t :: %__MODULE__{
    :"Name" => String.t,
    :"Data" => %{optional(String.t) => String.t}
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.GraphDriverData do
  def decode(value, _options) do
    value
  end
end

