# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.HealthConfig do
  @moduledoc """
  A test to perform to check that the container is healthy.
  """

  @derive [Poison.Encoder]
  defstruct [
    :Test,
    :Interval,
    :Timeout,
    :Retries,
    :StartPeriod
  ]

  @type t :: %__MODULE__{
          :Test => [String.t()],
          :Interval => integer(),
          :Timeout => integer(),
          :Retries => integer(),
          :StartPeriod => integer()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.HealthConfig do
  def decode(value, _options) do
    value
  end
end
