# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.Health do
  @moduledoc """
  Health stores information about the container&#39;s healthcheck results. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Status",
    :"FailingStreak",
    :"Log"
  ]

  @type t :: %__MODULE__{
    :"Status" => String.t,
    :"FailingStreak" => integer(),
    :"Log" => [HealthcheckResult]
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.Health do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Log", :list, DockerEngineAPI.Model.HealthcheckResult, options)
  end
end

