# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.HistoryResponseItem do
  @moduledoc """
  individual image layer information in response to ImageHistory operation
  """

  @derive [Poison.Encoder]
  defstruct [
    :Id,
    :Created,
    :CreatedBy,
    :Tags,
    :Size,
    :Comment
  ]

  @type t :: %__MODULE__{
          :Id => String.t(),
          :Created => integer(),
          :CreatedBy => String.t(),
          :Tags => [String.t()],
          :Size => integer(),
          :Comment => String.t()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.HistoryResponseItem do
  def decode(value, _options) do
    value
  end
end
