# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.IdResponse do
  @moduledoc """
  Response to an API call that returns just an Id
  """

  @derive [Poison.Encoder]
  defstruct [
    :Id
  ]

  @type t :: %__MODULE__{
          :Id => String.t()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.IdResponse do
  def decode(value, _options) do
    value
  end
end
