# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ImageSummary do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Id",
    :"ParentId",
    :"RepoTags",
    :"RepoDigests",
    :"Created",
    :"Size",
    :"SharedSize",
    :"VirtualSize",
    :"Labels",
    :"Containers"
  ]

  @type t :: %__MODULE__{
    :"Id" => String.t,
    :"ParentId" => String.t,
    :"RepoTags" => [String.t],
    :"RepoDigests" => [String.t],
    :"Created" => integer(),
    :"Size" => integer(),
    :"SharedSize" => integer(),
    :"VirtualSize" => integer(),
    :"Labels" => %{optional(String.t) => String.t},
    :"Containers" => integer()
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ImageSummary do
  def decode(value, _options) do
    value
  end
end

