# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ImageId do
  @moduledoc """
  Image ID or Digest
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ID"
  ]

  @type t :: %__MODULE__{
    :"ID" => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ImageId do
  def decode(value, _options) do
    value
  end
end

