# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ImageInspect do
  @moduledoc """
  Information about an image in the local image cache. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :Id,
    :RepoTags,
    :RepoDigests,
    :Parent,
    :Comment,
    :Created,
    :Container,
    :ContainerConfig,
    :DockerVersion,
    :Author,
    :Config,
    :Architecture,
    :Variant,
    :Os,
    :OsVersion,
    :Size,
    :VirtualSize,
    :GraphDriver,
    :RootFS,
    :Metadata
  ]

  @type t :: %__MODULE__{
          :Id => String.t(),
          :RepoTags => [String.t()],
          :RepoDigests => [String.t()],
          :Parent => String.t(),
          :Comment => String.t(),
          :Created => String.t(),
          :Container => String.t(),
          :ContainerConfig => ContainerConfig,
          :DockerVersion => String.t(),
          :Author => String.t(),
          :Config => ContainerConfig,
          :Architecture => String.t(),
          :Variant => String.t(),
          :Os => String.t(),
          :OsVersion => String.t(),
          :Size => integer(),
          :VirtualSize => integer(),
          :GraphDriver => GraphDriverData,
          :RootFS => ImageInspectRootFs,
          :Metadata => ImageInspectMetadata
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ImageInspect do
  import DockerEngineAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:ContainerConfig, :struct, DockerEngineAPI.Model.ContainerConfig, options)
    |> deserialize(:Config, :struct, DockerEngineAPI.Model.ContainerConfig, options)
    |> deserialize(:GraphDriver, :struct, DockerEngineAPI.Model.GraphDriverData, options)
    |> deserialize(:RootFS, :struct, DockerEngineAPI.Model.ImageInspectRootFs, options)
    |> deserialize(:Metadata, :struct, DockerEngineAPI.Model.ImageInspectMetadata, options)
  end
end
