# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ImageDeleteResponseItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Untagged",
    :"Deleted"
  ]

  @type t :: %__MODULE__{
    :"Untagged" => String.t,
    :"Deleted" => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ImageDeleteResponseItem do
  def decode(value, _options) do
    value
  end
end

