# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ImagePruneResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ImagesDeleted,
    :SpaceReclaimed
  ]

  @type t :: %__MODULE__{
          :ImagesDeleted => [ImageDeleteResponseItem],
          :SpaceReclaimed => integer()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ImagePruneResponse do
  import DockerEngineAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:ImagesDeleted, :list, DockerEngineAPI.Model.ImageDeleteResponseItem, options)
  end
end
