# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.IndexInfo do
  @moduledoc """
  IndexInfo contains information about a registry.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Name",
    :"Mirrors",
    :"Secure",
    :"Official"
  ]

  @type t :: %__MODULE__{
    :"Name" => String.t,
    :"Mirrors" => [String.t],
    :"Secure" => boolean(),
    :"Official" => boolean()
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.IndexInfo do
  def decode(value, _options) do
    value
  end
end

