# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.Ipam do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Driver,
    :Config,
    :Options
  ]

  @type t :: %__MODULE__{
          :Driver => String.t(),
          :Config => [IpamConfig],
          :Options => %{optional(String.t()) => String.t()}
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.Ipam do
  import DockerEngineAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Config, :list, DockerEngineAPI.Model.IpamConfig, options)
  end
end
