# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.IpamConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Subnet",
    :"IPRange",
    :"Gateway",
    :"AuxiliaryAddresses"
  ]

  @type t :: %__MODULE__{
    :"Subnet" => String.t,
    :"IPRange" => String.t,
    :"Gateway" => String.t,
    :"AuxiliaryAddresses" => %{optional(String.t) => String.t}
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.IpamConfig do
  def decode(value, _options) do
    value
  end
end

