# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.JoinTokens do
  @moduledoc """
  JoinTokens contains the tokens workers and managers need to join the swarm. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Worker",
    :"Manager"
  ]

  @type t :: %__MODULE__{
    :"Worker" => String.t,
    :"Manager" => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.JoinTokens do
  def decode(value, _options) do
    value
  end
end

