# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ManagerStatus do
  @moduledoc """
  ManagerStatus represents the status of a manager.  It provides the current status of a node&#39;s manager component, if the node is a manager. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Leader",
    :"Reachability",
    :"Addr"
  ]

  @type t :: %__MODULE__{
    :"Leader" => boolean(),
    :"Reachability" => Reachability,
    :"Addr" => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ManagerStatus do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Reachability", :struct, DockerEngineAPI.Model.Reachability, options)
  end
end

