# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.MountVolumeOptions do
  @moduledoc """
  Optional configuration for the &#x60;volume&#x60; type.
  """

  @derive [Poison.Encoder]
  defstruct [
    :NoCopy,
    :Labels,
    :DriverConfig
  ]

  @type t :: %__MODULE__{
          :NoCopy => boolean(),
          :Labels => %{optional(String.t()) => String.t()},
          :DriverConfig => MountVolumeOptionsDriverConfig
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.MountVolumeOptions do
  import DockerEngineAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :DriverConfig,
      :struct,
      DockerEngineAPI.Model.MountVolumeOptionsDriverConfig,
      options
    )
  end
end
