# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.MountTmpfsOptions do
  @moduledoc """
  Optional configuration for the &#x60;tmpfs&#x60; type.
  """

  @derive [Poison.Encoder]
  defstruct [
    :SizeBytes,
    :Mode
  ]

  @type t :: %__MODULE__{
          :SizeBytes => integer(),
          :Mode => integer()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.MountTmpfsOptions do
  def decode(value, _options) do
    value
  end
end
