# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.MountPoint do
  @moduledoc """
  MountPoint represents a mount point configuration inside the container. This is used for reporting the mountpoints in use by a container. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Type",
    :"Name",
    :"Source",
    :"Destination",
    :"Driver",
    :"Mode",
    :"RW",
    :"Propagation"
  ]

  @type t :: %__MODULE__{
    :"Type" => String.t,
    :"Name" => String.t,
    :"Source" => String.t,
    :"Destination" => String.t,
    :"Driver" => String.t,
    :"Mode" => String.t,
    :"RW" => boolean(),
    :"Propagation" => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.MountPoint do
  def decode(value, _options) do
    value
  end
end

