# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.MountVolumeOptionsDriverConfig do
  @moduledoc """
  Map of driver specific options
  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :Options
  ]

  @type t :: %__MODULE__{
          :Name => String.t(),
          :Options => %{optional(String.t()) => String.t()}
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.MountVolumeOptionsDriverConfig do
  def decode(value, _options) do
    value
  end
end
