# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.NetworkConnectRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Container,
    :EndpointConfig
  ]

  @type t :: %__MODULE__{
          :Container => String.t(),
          :EndpointConfig => EndpointSettings
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.NetworkConnectRequest do
  import DockerEngineAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:EndpointConfig, :struct, DockerEngineAPI.Model.EndpointSettings, options)
  end
end
