# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.NetworkingConfig do
  @moduledoc """
  NetworkingConfig represents the container&#39;s networking configuration for each of its interfaces. It is used for the networking configs specified in the &#x60;docker create&#x60; and &#x60;docker network connect&#x60; commands. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :EndpointsConfig
  ]

  @type t :: %__MODULE__{
          :EndpointsConfig => %{optional(String.t()) => EndpointSettings}
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.NetworkingConfig do
  import DockerEngineAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:EndpointsConfig, :map, DockerEngineAPI.Model.EndpointSettings, options)
  end
end
