# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.NetworkContainer do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :EndpointID,
    :MacAddress,
    :IPv4Address,
    :IPv6Address
  ]

  @type t :: %__MODULE__{
          :Name => String.t(),
          :EndpointID => String.t(),
          :MacAddress => String.t(),
          :IPv4Address => String.t(),
          :IPv6Address => String.t()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.NetworkContainer do
  def decode(value, _options) do
    value
  end
end
