# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.NetworkCreateResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Id,
    :Warning
  ]

  @type t :: %__MODULE__{
          :Id => String.t(),
          :Warning => String.t()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.NetworkCreateResponse do
  def decode(value, _options) do
    value
  end
end
