# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.NetworkDisconnectRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Container",
    :"Force"
  ]

  @type t :: %__MODULE__{
    :"Container" => String.t,
    :"Force" => boolean()
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.NetworkDisconnectRequest do
  def decode(value, _options) do
    value
  end
end

