# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.NetworkPruneResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :NetworksDeleted
  ]

  @type t :: %__MODULE__{
          :NetworksDeleted => [String.t()]
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.NetworkPruneResponse do
  def decode(value, _options) do
    value
  end
end
