# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.NodeDescription do
  @moduledoc """
  NodeDescription encapsulates the properties of the Node as reported by the agent. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Hostname",
    :"Platform",
    :"Resources",
    :"Engine",
    :"TLSInfo"
  ]

  @type t :: %__MODULE__{
    :"Hostname" => String.t,
    :"Platform" => Platform,
    :"Resources" => ResourceObject,
    :"Engine" => EngineDescription,
    :"TLSInfo" => TlsInfo
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.NodeDescription do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Platform", :struct, DockerEngineAPI.Model.Platform, options)
    |> deserialize(:"Resources", :struct, DockerEngineAPI.Model.ResourceObject, options)
    |> deserialize(:"Engine", :struct, DockerEngineAPI.Model.EngineDescription, options)
    |> deserialize(:"TLSInfo", :struct, DockerEngineAPI.Model.TlsInfo, options)
  end
end

