# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.OciDescriptor do
  @moduledoc """
  A descriptor struct containing digest, media type, and size, as defined in the [OCI Content Descriptors Specification](https://github.com/opencontainers/image-spec/blob/v1.0.1/descriptor.md). 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"mediaType",
    :"digest",
    :"size"
  ]

  @type t :: %__MODULE__{
    :"mediaType" => String.t,
    :"digest" => String.t,
    :"size" => integer()
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.OciDescriptor do
  def decode(value, _options) do
    value
  end
end

