# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.OciPlatform do
  @moduledoc """
  Describes the platform which the image in the manifest runs on, as defined in the [OCI Image Index Specification](https://github.com/opencontainers/image-spec/blob/v1.0.1/image-index.md). 
  """

  @derive [Poison.Encoder]
  defstruct [
    :architecture,
    :os,
    :"os.version",
    :"os.features",
    :variant
  ]

  @type t :: %__MODULE__{
          :architecture => String.t(),
          :os => String.t(),
          :"os.version" => String.t(),
          :"os.features" => [String.t()],
          :variant => String.t()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.OciPlatform do
  def decode(value, _options) do
    value
  end
end
