# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.PeerNode do
  @moduledoc """
  Represents a peer-node in the swarm
  """

  @derive [Poison.Encoder]
  defstruct [
    :NodeID,
    :Addr
  ]

  @type t :: %__MODULE__{
          :NodeID => String.t(),
          :Addr => String.t()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.PeerNode do
  def decode(value, _options) do
    value
  end
end
