# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.Platform do
  @moduledoc """
  Platform represents the platform (Arch/OS). 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Architecture",
    :"OS"
  ]

  @type t :: %__MODULE__{
    :"Architecture" => String.t,
    :"OS" => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.Platform do
  def decode(value, _options) do
    value
  end
end

