# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.PluginConfigNetwork do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Type
  ]

  @type t :: %__MODULE__{
          :Type => String.t()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.PluginConfigNetwork do
  def decode(value, _options) do
    value
  end
end
