# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.PluginConfigUser do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :UID,
    :GID
  ]

  @type t :: %__MODULE__{
          :UID => integer(),
          :GID => integer()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.PluginConfigUser do
  def decode(value, _options) do
    value
  end
end
