# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.Plugin do
  @moduledoc """
  A plugin for the Engine API
  """

  @derive [Poison.Encoder]
  defstruct [
    :Id,
    :Name,
    :Enabled,
    :Settings,
    :PluginReference,
    :Config
  ]

  @type t :: %__MODULE__{
          :Id => String.t(),
          :Name => String.t(),
          :Enabled => boolean(),
          :Settings => PluginSettings,
          :PluginReference => String.t(),
          :Config => PluginConfig
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.Plugin do
  import DockerEngineAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Settings, :struct, DockerEngineAPI.Model.PluginSettings, options)
    |> deserialize(:Config, :struct, DockerEngineAPI.Model.PluginConfig, options)
  end
end
