# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.PluginInterfaceType do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Prefix",
    :"Capability",
    :"Version"
  ]

  @type t :: %__MODULE__{
    :"Prefix" => String.t,
    :"Capability" => String.t,
    :"Version" => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.PluginInterfaceType do
  def decode(value, _options) do
    value
  end
end

