# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.PluginSettings do
  @moduledoc """
  Settings that can be modified by users.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Mounts",
    :"Env",
    :"Args",
    :"Devices"
  ]

  @type t :: %__MODULE__{
    :"Mounts" => [PluginMount],
    :"Env" => [String.t],
    :"Args" => [String.t],
    :"Devices" => [PluginDevice]
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.PluginSettings do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Mounts", :list, DockerEngineAPI.Model.PluginMount, options)
    |> deserialize(:"Devices", :list, DockerEngineAPI.Model.PluginDevice, options)
  end
end

