# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.PluginMount do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :Description,
    :Settable,
    :Source,
    :Destination,
    :Type,
    :Options
  ]

  @type t :: %__MODULE__{
          :Name => String.t(),
          :Description => String.t(),
          :Settable => [String.t()],
          :Source => String.t(),
          :Destination => String.t(),
          :Type => String.t(),
          :Options => [String.t()]
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.PluginMount do
  def decode(value, _options) do
    value
  end
end
