# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.PluginConfigRootfs do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :diff_ids
  ]

  @type t :: %__MODULE__{
          :type => String.t(),
          :diff_ids => [String.t()]
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.PluginConfigRootfs do
  def decode(value, _options) do
    value
  end
end
