# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.PluginsInfo do
  @moduledoc """
  Available plugins per type.  &lt;p&gt;&lt;br /&gt;&lt;/p&gt;  &gt; **Note**: Only unmanaged (V1) plugins are included in this list. &gt; V1 plugins are \&quot;lazily\&quot; loaded, and are not returned in this list &gt; if there is no resource using the plugin. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :Volume,
    :Network,
    :Authorization,
    :Log
  ]

  @type t :: %__MODULE__{
          :Volume => [String.t()],
          :Network => [String.t()],
          :Authorization => [String.t()],
          :Log => [String.t()]
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.PluginsInfo do
  def decode(value, _options) do
    value
  end
end
