# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.PluginConfigLinux do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Capabilities,
    :AllowAllDevices,
    :Devices
  ]

  @type t :: %__MODULE__{
          :Capabilities => [String.t()],
          :AllowAllDevices => boolean(),
          :Devices => [PluginDevice]
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.PluginConfigLinux do
  import DockerEngineAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Devices, :list, DockerEngineAPI.Model.PluginDevice, options)
  end
end
