# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.Port do
  @moduledoc """
  An open port on a container
  """

  @derive [Poison.Encoder]
  defstruct [
    :"IP",
    :"PrivatePort",
    :"PublicPort",
    :"Type"
  ]

  @type t :: %__MODULE__{
    :"IP" => String.t,
    :"PrivatePort" => integer(),
    :"PublicPort" => integer(),
    :"Type" => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.Port do
  def decode(value, _options) do
    value
  end
end

