# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ProcessConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"privileged",
    :"user",
    :"tty",
    :"entrypoint",
    :"arguments"
  ]

  @type t :: %__MODULE__{
    :"privileged" => boolean(),
    :"user" => String.t,
    :"tty" => boolean(),
    :"entrypoint" => String.t,
    :"arguments" => [String.t]
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ProcessConfig do
  def decode(value, _options) do
    value
  end
end

