# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ProgressDetail do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :current,
    :total
  ]

  @type t :: %__MODULE__{
          :current => integer(),
          :total => integer()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ProgressDetail do
  def decode(value, _options) do
    value
  end
end
