# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.PushImageInfo do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :error,
    :status,
    :progress,
    :progressDetail
  ]

  @type t :: %__MODULE__{
          :error => String.t(),
          :status => String.t(),
          :progress => String.t(),
          :progressDetail => ProgressDetail
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.PushImageInfo do
  import DockerEngineAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:progressDetail, :struct, DockerEngineAPI.Model.ProgressDetail, options)
  end
end
