# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ResourcesUlimits do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :Soft,
    :Hard
  ]

  @type t :: %__MODULE__{
          :Name => String.t(),
          :Soft => integer(),
          :Hard => integer()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ResourcesUlimits do
  def decode(value, _options) do
    value
  end
end
