# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ResourcesBlkioWeightDevice do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Path",
    :"Weight"
  ]

  @type t :: %__MODULE__{
    :"Path" => String.t,
    :"Weight" => integer()
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ResourcesBlkioWeightDevice do
  def decode(value, _options) do
    value
  end
end

