# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.RestartPolicy do
  @moduledoc """
  The behavior to apply when the container exits. The default is not to restart.  An ever increasing delay (double the previous delay, starting at 100ms) is added before each restart to prevent flooding the server. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Name",
    :"MaximumRetryCount"
  ]

  @type t :: %__MODULE__{
    :"Name" => String.t,
    :"MaximumRetryCount" => integer()
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.RestartPolicy do
  def decode(value, _options) do
    value
  end
end

