# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ServiceSpecModeReplicatedJob do
  @moduledoc """
  The mode used for services with a finite number of tasks that run to a completed state. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"MaxConcurrent",
    :"TotalCompletions"
  ]

  @type t :: %__MODULE__{
    :"MaxConcurrent" => integer(),
    :"TotalCompletions" => integer()
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ServiceSpecModeReplicatedJob do
  def decode(value, _options) do
    value
  end
end

