# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ServiceSpecRollbackConfig do
  @moduledoc """
  Specification for the rollback strategy of the service.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Parallelism",
    :"Delay",
    :"FailureAction",
    :"Monitor",
    :"MaxFailureRatio",
    :"Order"
  ]

  @type t :: %__MODULE__{
    :"Parallelism" => integer(),
    :"Delay" => integer(),
    :"FailureAction" => String.t,
    :"Monitor" => integer(),
    :"MaxFailureRatio" => float(),
    :"Order" => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ServiceSpecRollbackConfig do
  def decode(value, _options) do
    value
  end
end

