# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ServiceSpecMode do
  @moduledoc """
  Scheduling mode for the service.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Replicated",
    :"Global",
    :"ReplicatedJob",
    :"GlobalJob"
  ]

  @type t :: %__MODULE__{
    :"Replicated" => ServiceSpecModeReplicated,
    :"Global" => Object,
    :"ReplicatedJob" => ServiceSpecModeReplicatedJob,
    :"GlobalJob" => Object
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ServiceSpecMode do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Replicated", :struct, DockerEngineAPI.Model.ServiceSpecModeReplicated, options)
    |> deserialize(:"Global", :struct, DockerEngineAPI.Model.Object, options)
    |> deserialize(:"ReplicatedJob", :struct, DockerEngineAPI.Model.ServiceSpecModeReplicatedJob, options)
    |> deserialize(:"GlobalJob", :struct, DockerEngineAPI.Model.Object, options)
  end
end

