# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ServiceServiceStatus do
  @moduledoc """
  The status of the service&#39;s tasks. Provided only when requested as part of a ServiceList operation. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :RunningTasks,
    :DesiredTasks,
    :CompletedTasks
  ]

  @type t :: %__MODULE__{
          :RunningTasks => integer(),
          :DesiredTasks => integer(),
          :CompletedTasks => integer()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ServiceServiceStatus do
  def decode(value, _options) do
    value
  end
end
