# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ServiceCreateResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ID,
    :Warning
  ]

  @type t :: %__MODULE__{
          :ID => String.t(),
          :Warning => String.t()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ServiceCreateResponse do
  def decode(value, _options) do
    value
  end
end
