# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ServiceJobStatus do
  @moduledoc """
  The status of the service when it is in one of ReplicatedJob or GlobalJob modes. Absent on Replicated and Global mode services. The JobIteration is an ObjectVersion, but unlike the Service&#39;s version, does not need to be sent with an update request. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"JobIteration",
    :"LastExecution"
  ]

  @type t :: %__MODULE__{
    :"JobIteration" => ObjectVersion,
    :"LastExecution" => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ServiceJobStatus do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"JobIteration", :struct, DockerEngineAPI.Model.ObjectVersion, options)
  end
end

