# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ServiceUpdateStatus do
  @moduledoc """
  The status of a service update.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"State",
    :"StartedAt",
    :"CompletedAt",
    :"Message"
  ]

  @type t :: %__MODULE__{
    :"State" => String.t,
    :"StartedAt" => String.t,
    :"CompletedAt" => String.t,
    :"Message" => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ServiceUpdateStatus do
  def decode(value, _options) do
    value
  end
end

