# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.SwarmSpecRaft do
  @moduledoc """
  Raft configuration.
  """

  @derive [Poison.Encoder]
  defstruct [
    :SnapshotInterval,
    :KeepOldSnapshots,
    :LogEntriesForSlowFollowers,
    :ElectionTick,
    :HeartbeatTick
  ]

  @type t :: %__MODULE__{
          :SnapshotInterval => integer(),
          :KeepOldSnapshots => integer(),
          :LogEntriesForSlowFollowers => integer(),
          :ElectionTick => integer(),
          :HeartbeatTick => integer()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SwarmSpecRaft do
  def decode(value, _options) do
    value
  end
end
