# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.SwarmSpecTaskDefaults do
  @moduledoc """
  Defaults for creating tasks in this cluster.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"LogDriver"
  ]

  @type t :: %__MODULE__{
    :"LogDriver" => SwarmSpecTaskDefaultsLogDriver
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SwarmSpecTaskDefaults do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"LogDriver", :struct, DockerEngineAPI.Model.SwarmSpecTaskDefaultsLogDriver, options)
  end
end

