# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.SwarmSpecOrchestration do
  @moduledoc """
  Orchestration configuration.
  """

  @derive [Poison.Encoder]
  defstruct [
    :TaskHistoryRetentionLimit
  ]

  @type t :: %__MODULE__{
          :TaskHistoryRetentionLimit => integer()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SwarmSpecOrchestration do
  def decode(value, _options) do
    value
  end
end
