# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.SwarmSpecCaConfigExternalCas do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Protocol",
    :"URL",
    :"Options",
    :"CACert"
  ]

  @type t :: %__MODULE__{
    :"Protocol" => String.t,
    :"URL" => String.t,
    :"Options" => %{optional(String.t) => String.t},
    :"CACert" => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SwarmSpecCaConfigExternalCas do
  def decode(value, _options) do
    value
  end
end

