# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.SwarmJoinRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ListenAddr",
    :"AdvertiseAddr",
    :"DataPathAddr",
    :"RemoteAddrs",
    :"JoinToken"
  ]

  @type t :: %__MODULE__{
    :"ListenAddr" => String.t,
    :"AdvertiseAddr" => String.t,
    :"DataPathAddr" => String.t,
    :"RemoteAddrs" => [String.t],
    :"JoinToken" => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SwarmJoinRequest do
  def decode(value, _options) do
    value
  end
end

