# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.SwarmSpecCaConfig do
  @moduledoc """
  CA configuration.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"NodeCertExpiry",
    :"ExternalCAs",
    :"SigningCACert",
    :"SigningCAKey",
    :"ForceRotate"
  ]

  @type t :: %__MODULE__{
    :"NodeCertExpiry" => integer(),
    :"ExternalCAs" => [SwarmSpecCaConfigExternalCas],
    :"SigningCACert" => String.t,
    :"SigningCAKey" => String.t,
    :"ForceRotate" => integer()
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SwarmSpecCaConfig do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"ExternalCAs", :list, DockerEngineAPI.Model.SwarmSpecCaConfigExternalCas, options)
  end
end

