# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.SwarmSpecTaskDefaultsLogDriver do
  @moduledoc """
  The log driver to use for tasks created in the orchestrator if unspecified by a service.  Updating this value only affects new tasks. Existing tasks continue to use their previously configured log driver until recreated. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :Options
  ]

  @type t :: %__MODULE__{
          :Name => String.t(),
          :Options => %{optional(String.t()) => String.t()}
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SwarmSpecTaskDefaultsLogDriver do
  def decode(value, _options) do
    value
  end
end
