# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.SwarmSpecEncryptionConfig do
  @moduledoc """
  Parameters related to encryption-at-rest.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"AutoLockManagers"
  ]

  @type t :: %__MODULE__{
    :"AutoLockManagers" => boolean()
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SwarmSpecEncryptionConfig do
  def decode(value, _options) do
    value
  end
end

