# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.SwarmInfo do
  @moduledoc """
  Represents generic information about swarm. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :NodeID,
    :NodeAddr,
    :LocalNodeState,
    :ControlAvailable,
    :Error,
    :RemoteManagers,
    :Nodes,
    :Managers,
    :Cluster
  ]

  @type t :: %__MODULE__{
          :NodeID => String.t(),
          :NodeAddr => String.t(),
          :LocalNodeState => LocalNodeState,
          :ControlAvailable => boolean(),
          :Error => String.t(),
          :RemoteManagers => [PeerNode],
          :Nodes => integer(),
          :Managers => integer(),
          :Cluster => ClusterInfo
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SwarmInfo do
  import DockerEngineAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:LocalNodeState, :struct, DockerEngineAPI.Model.LocalNodeState, options)
    |> deserialize(:RemoteManagers, :list, DockerEngineAPI.Model.PeerNode, options)
    |> deserialize(:Cluster, :struct, DockerEngineAPI.Model.ClusterInfo, options)
  end
end
