# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.SwarmSpecDispatcher do
  @moduledoc """
  Dispatcher configuration.
  """

  @derive [Poison.Encoder]
  defstruct [
    :HeartbeatPeriod
  ]

  @type t :: %__MODULE__{
          :HeartbeatPeriod => integer()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SwarmSpecDispatcher do
  def decode(value, _options) do
    value
  end
end
