# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.SystemVersionPlatform do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Name"
  ]

  @type t :: %__MODULE__{
    :"Name" => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SystemVersionPlatform do
  def decode(value, _options) do
    value
  end
end

