# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.SystemVersionComponents do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Name",
    :"Version",
    :"Details"
  ]

  @type t :: %__MODULE__{
    :"Name" => String.t,
    :"Version" => String.t,
    :"Details" => Object
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SystemVersionComponents do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Details", :struct, DockerEngineAPI.Model.Object, options)
  end
end

