# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.SystemAuthResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Status",
    :"IdentityToken"
  ]

  @type t :: %__MODULE__{
    :"Status" => String.t,
    :"IdentityToken" => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SystemAuthResponse do
  def decode(value, _options) do
    value
  end
end

