# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.TaskSpecPluginSpec do
  @moduledoc """
  Plugin spec for the service.  *(Experimental release only.)*  &lt;p&gt;&lt;br /&gt;&lt;/p&gt;  &gt; **Note**: ContainerSpec, NetworkAttachmentSpec, and PluginSpec are &gt; mutually exclusive. PluginSpec is only used when the Runtime field &gt; is set to &#x60;plugin&#x60;. NetworkAttachmentSpec is used when the Runtime &gt; field is set to &#x60;attachment&#x60;. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :Remote,
    :Disabled,
    :PluginPrivilege
  ]

  @type t :: %__MODULE__{
          :Name => String.t(),
          :Remote => String.t(),
          :Disabled => boolean(),
          :PluginPrivilege => [PluginPrivilege]
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.TaskSpecPluginSpec do
  import DockerEngineAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:PluginPrivilege, :list, DockerEngineAPI.Model.PluginPrivilege, options)
  end
end
