# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.TaskSpecContainerSpecConfigs do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :File,
    :Runtime,
    :ConfigID,
    :ConfigName
  ]

  @type t :: %__MODULE__{
          :File => TaskSpecContainerSpecFile1,
          :Runtime => Object,
          :ConfigID => String.t(),
          :ConfigName => String.t()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.TaskSpecContainerSpecConfigs do
  import DockerEngineAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:File, :struct, DockerEngineAPI.Model.TaskSpecContainerSpecFile1, options)
    |> deserialize(:Runtime, :struct, DockerEngineAPI.Model.Object, options)
  end
end
