# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.TaskSpecRestartPolicy do
  @moduledoc """
  Specification for the restart policy which applies to containers created as part of this service. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Condition",
    :"Delay",
    :"MaxAttempts",
    :"Window"
  ]

  @type t :: %__MODULE__{
    :"Condition" => String.t,
    :"Delay" => integer(),
    :"MaxAttempts" => integer(),
    :"Window" => integer()
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.TaskSpecRestartPolicy do
  def decode(value, _options) do
    value
  end
end

