# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.TaskSpecPlacementPreferences do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Spread"
  ]

  @type t :: %__MODULE__{
    :"Spread" => TaskSpecPlacementSpread
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.TaskSpecPlacementPreferences do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Spread", :struct, DockerEngineAPI.Model.TaskSpecPlacementSpread, options)
  end
end

