# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.TaskSpecContainerSpecDnsConfig do
  @moduledoc """
  Specification for DNS related configurations in resolver configuration file (&#x60;resolv.conf&#x60;). 
  """

  @derive [Poison.Encoder]
  defstruct [
    :Nameservers,
    :Search,
    :Options
  ]

  @type t :: %__MODULE__{
          :Nameservers => [String.t()],
          :Search => [String.t()],
          :Options => [String.t()]
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.TaskSpecContainerSpecDnsConfig do
  def decode(value, _options) do
    value
  end
end
