# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.TaskStatus do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Timestamp,
    :State,
    :Message,
    :Err,
    :ContainerStatus
  ]

  @type t :: %__MODULE__{
          :Timestamp => String.t(),
          :State => TaskState,
          :Message => String.t(),
          :Err => String.t(),
          :ContainerStatus => TaskStatusContainerStatus
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.TaskStatus do
  import DockerEngineAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:State, :struct, DockerEngineAPI.Model.TaskState, options)
    |> deserialize(
      :ContainerStatus,
      :struct,
      DockerEngineAPI.Model.TaskStatusContainerStatus,
      options
    )
  end
end
