# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.TaskSpecContainerSpecPrivilegesSeLinuxContext do
  @moduledoc """
  SELinux labels of the container
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Disable",
    :"User",
    :"Role",
    :"Type",
    :"Level"
  ]

  @type t :: %__MODULE__{
    :"Disable" => boolean(),
    :"User" => String.t,
    :"Role" => String.t,
    :"Type" => String.t,
    :"Level" => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.TaskSpecContainerSpecPrivilegesSeLinuxContext do
  def decode(value, _options) do
    value
  end
end

