# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.TaskSpecContainerSpecFile do
  @moduledoc """
  File represents a specific target that is backed by a file. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Name",
    :"UID",
    :"GID",
    :"Mode"
  ]

  @type t :: %__MODULE__{
    :"Name" => String.t,
    :"UID" => String.t,
    :"GID" => String.t,
    :"Mode" => integer()
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.TaskSpecContainerSpecFile do
  def decode(value, _options) do
    value
  end
end

