# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.TaskSpecNetworkAttachmentSpec do
  @moduledoc """
  Read-only spec type for non-swarm containers attached to swarm overlay networks.  &lt;p&gt;&lt;br /&gt;&lt;/p&gt;  &gt; **Note**: ContainerSpec, NetworkAttachmentSpec, and PluginSpec are &gt; mutually exclusive. PluginSpec is only used when the Runtime field &gt; is set to &#x60;plugin&#x60;. NetworkAttachmentSpec is used when the Runtime &gt; field is set to &#x60;attachment&#x60;. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ContainerID"
  ]

  @type t :: %__MODULE__{
    :"ContainerID" => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.TaskSpecNetworkAttachmentSpec do
  def decode(value, _options) do
    value
  end
end

