# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.ThrottleDevice do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Path,
    :Rate
  ]

  @type t :: %__MODULE__{
          :Path => String.t(),
          :Rate => integer()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ThrottleDevice do
  def decode(value, _options) do
    value
  end
end
