# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.TlsInfo do
  @moduledoc """
  Information about the issuer of leaf TLS certificates and the trusted root CA certificate. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :"TrustRoot",
    :"CertIssuerSubject",
    :"CertIssuerPublicKey"
  ]

  @type t :: %__MODULE__{
    :"TrustRoot" => String.t,
    :"CertIssuerSubject" => String.t,
    :"CertIssuerPublicKey" => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.TlsInfo do
  def decode(value, _options) do
    value
  end
end

