# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.VolumeUsageData do
  @moduledoc """
  Usage details about the volume. This information is used by the &#x60;GET /system/df&#x60; endpoint, and omitted in other endpoints. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :Size,
    :RefCount
  ]

  @type t :: %__MODULE__{
          :Size => integer(),
          :RefCount => integer()
        }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.VolumeUsageData do
  def decode(value, _options) do
    value
  end
end
