# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule DockerEngineAPI.Model.VolumeListResponse do
  @moduledoc """
  Volume list response
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Volumes",
    :"Warnings"
  ]

  @type t :: %__MODULE__{
    :"Volumes" => [Volume],
    :"Warnings" => [String.t]
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.VolumeListResponse do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Volumes", :list, DockerEngineAPI.Model.Volume, options)
  end
end

